INSERT INTO SERVICIO_ENTITY (ID, NOMBRE) VALUES (101, 'Andres');
INSERT INTO MASCOTA_ENTITY (ID, FECHA_NACIMIENTO, NOMBRE, RAZA, UBICACION, DUENIO_ID) VALUES (102,'2020-09-09', 'Milo', 'Springer Spaniel', 'Calle 2', null);
insert into VETERINARIO_ENTITY (ID, CALIFICACION, CERTIFICADO_ENTRENAMIENTO, ESPECIALIDAD, EXPERIENCIA_PREVIA, NOMBRE ) values (100, 5, 'a', 'v', '', 'PepitoPerez');
insert into CONTACTO_ENTITY (ID,CORREO,TELEFONO,CLIENTE_ID,EMPRESA_ID,VETERINARIO_ID) values (100, 'j.marinm@uniandes.edu.co', '1232132135', null, null , 100);
insert into CITA_ENTITY (ID, FECHA, ESTADO, COSTO, DISPONIBLE, DURACION) values (100,'2021-09-09',0,5000.0,false,120);
insert into AGENDA_ENTITY (ID, NUMERO_CITAS_PENDIENTES, NUMERO_CITAS_REALIZADAS, NUMERO_CITAS_CANCELADAS) values (100,0,1,2);
