INSERT INTO VETERINARIO_ENTITY (ID ,CALIFICACION ,CERTIFICADO_ENTRENAMIENTO ,ESPECIALIDAD ,EXPERIENCIA_PREVIA ,NOMBRE) VALUES (100, 3.4, 'saadasjdas', 'asdasdas', 'qeqwe', 'Roberto');
INSERT INTO VETERINARIO_ENTITY (ID ,CALIFICACION ,CERTIFICADO_ENTRENAMIENTO ,ESPECIALIDAD ,EXPERIENCIA_PREVIA ,NOMBRE) VALUES (101, 3.9, 'aaasds', 'xmxmxm', 'qaaaeqwe', 'Antonia');
INSERT INTO VETERINARIO_ENTITY (ID ,CALIFICACION ,CERTIFICADO_ENTRENAMIENTO ,ESPECIALIDAD ,EXPERIENCIA_PREVIA ,NOMBRE) VALUES (102, 4.1, 'asdnnc', 'jhndif', 'qeqweccc', 'Calamardo');

INSERT INTO CONTACTO_ENTITY (ID, CORREO, TELEFONO, VETERINARIO_ID ) VALUES (100, 'roberto@gmail.com', '+57 0987654321', 100);
INSERT INTO CONTACTO_ENTITY (ID, CORREO, TELEFONO, VETERINARIO_ID ) VALUES (101, 'antonia@gmail.com', '+57 7519203219', 101);
INSERT INTO CONTACTO_ENTITY (ID, CORREO, TELEFONO, VETERINARIO_ID ) VALUES (102, 'calamardo@gmail.com', '+57 7471288838', 102);

INSERT INTO CLIENTE_ENTITY (ID, NOMBRE, CALIFICACION) VALUES (100, 'Valentina Paternostro', 3.8);
INSERT INTO CLIENTE_ENTITY (ID, NOMBRE, CALIFICACION) VALUES (101, 'Laura Martínez', 4.0);
INSERT INTO CLIENTE_ENTITY (ID, NOMBRE, CALIFICACION) VALUES (102, 'Lina Orozco', 3.5);

INSERT INTO EMPRESA_CONVENIO_ENTITY (ID, NOMBRE, NIT, SERVICIO) VALUES (102, 'MediDogs', 7788, 'Operaciones' );
INSERT INTO EMPRESA_CONVENIO_ENTITY (ID, NOMBRE, NIT, SERVICIO) VALUES (103, 'Animals', 77389, 'Vacunación' );
INSERT INTO EMPRESA_CONVENIO_ENTITY (ID, NOMBRE, NIT, SERVICIO) VALUES (104, 'Dogs&Cats', 75790, 'Analisis' );

INSERT INTO MASCOTA_ENTITY (ID ,FECHA_NACIMIENTO ,NOMBRE ,RAZA ,UBICACION ,DUENIO_ID ) VALUES ( 100, '2020-10-10', 'Michi', 'Naranja', 'No se', 100);
INSERT INTO MASCOTA_ENTITY (ID ,FECHA_NACIMIENTO ,NOMBRE ,RAZA ,UBICACION ,DUENIO_ID ) VALUES ( 101, '2019-10-10', 'Firulais', 'Perro', 'No se', 101);
INSERT INTO MASCOTA_ENTITY (ID ,FECHA_NACIMIENTO ,NOMBRE ,RAZA ,UBICACION ,DUENIO_ID ) VALUES ( 102, '2018-10-10', 'Mumble', 'Pinguino', 'No se', 101);

INSERT INTO SERVICIO_ENTITY (ID ,NOMBRE ) VALUES ( 100, 'Vacunacion');
INSERT INTO SERVICIO_ENTITY (ID ,NOMBRE ) VALUES ( 101, 'Cirujia');
INSERT INTO SERVICIO_ENTITY (ID ,NOMBRE ) VALUES ( 102, 'Servicio bueno');

INSERT INTO CITA_ENTITY (ID, FECHA, ESTADO, COSTO, DISPONIBLE, DURACION) VALUES (100,'2021-09-09',0,5000.0,false,120);
INSERT INTO CITA_ENTITY (ID, FECHA, ESTADO, COSTO, DISPONIBLE, DURACION) VALUES (101,'2020-09-09',1,5000.0,true,60);
INSERT INTO CITA_ENTITY (ID, FECHA, ESTADO, COSTO, DISPONIBLE, DURACION) VALUES (102,'2019-09-09',2,5000.0,true,180);

INSERT INTO AGENDA_ENTITY (ID, NUMERO_CITAS_PENDIENTES, NUMERO_CITAS_REALIZADAS, NUMERO_CITAS_CANCELADAS, VETERINARIO_ID) VALUES (100,0,1,2,100);
INSERT INTO AGENDA_ENTITY (ID, NUMERO_CITAS_PENDIENTES, NUMERO_CITAS_REALIZADAS, NUMERO_CITAS_CANCELADAS, VETERINARIO_ID) VALUES (101,1,1,1,101);
INSERT INTO AGENDA_ENTITY (ID, NUMERO_CITAS_PENDIENTES, NUMERO_CITAS_REALIZADAS, NUMERO_CITAS_CANCELADAS, VETERINARIO_ID) VALUES (102,2,1,0,102);

INSERT INTO REGISTRO_MEDICO_ENTITY(ID, FECHA_EXPEDICION, IDENTIFICACION, IMAGEN,VETERINARIO_ID) VALUES(131,'2021-05-09','1000203942','foto',100);
INSERT INTO REGISTRO_MEDICO_ENTITY(ID, FECHA_EXPEDICION, IDENTIFICACION, IMAGEN,VETERINARIO_ID) VALUES(132,'2001-09-12','1000201322','foto 1',101);
INSERT INTO REGISTRO_MEDICO_ENTITY(ID, FECHA_EXPEDICION, IDENTIFICACION, IMAGEN,VETERINARIO_ID) VALUES(133,'2030-10-08','1000476574','foto 2',102);


INSERT INTO CALIFICACION_ENTITY(ID, CREADOR,FECHA, PUNTAJE, CLIENTE_CALIFICADO_ID,VETERINARIO_CALIFICADO_ID,DESCRIPCION) VALUES(141,'Pepe','2021-10-09',3 ,null,101,'Un veterinario normal');
INSERT INTO CALIFICACION_ENTITY(ID, CREADOR,FECHA, PUNTAJE, CLIENTE_CALIFICADO_ID,VETERINARIO_CALIFICADO_ID,DESCRIPCION) VALUES(142,'Jenkins','2021-02-01',3 ,102,null,'Un cliente un poco sobreprotector');
INSERT INTO CALIFICACION_ENTITY(ID, CREADOR,FECHA, PUNTAJE, CLIENTE_CALIFICADO_ID,VETERINARIO_CALIFICADO_ID,DESCRIPCION) VALUES(143,'Dios','2021-09-07',3 ,null,100,'A mi perro le quedo doliendo la pata despues de la inyeccion');